### ISSUE TITLE
How to push completed tasks into the repo?

### ISSUE THREAD

**Issue by michitomo** [shortintern2019/intern-tutorial#4]
I don't get following instruction.
> For Spring Frame Tutorial, create a new branch from the master branch. Branch name should be in format of "feature/FIRSTNAME_LASTNAME". Once you complete the tutorial push your work to the GitHub repository.

Do you want them to create new branch and push into this repository? If so, how they should separately store every tutorial? In general, Maven project should have pom.xml at the root of Git repo.
If you meant to store multiple projects under this repo, it's easier to understand if we have empty directories for every assignment here, though IDEs may not recognize the structure automatically.

**Comment by scranton01** [comment]
I figured even interns push their work, no one will check so I omitted push part of this tutorial
